name = "density_of_shapes"
version = "0.1.0"
defaultTargets = ["ShapesFormal"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.0-rc1"

[[lean_lib]]
name = "ShapesFormal"
srcDir = "FormalShapes"
roots = [
  "Main",
  "External.CusickRegulator",
  "External.BananaDensity",
  "SageCalculations"
]
