import ABCOrders
import Mathlib.RingTheory.Localization.Finiteness
import Mathlib.RingTheory.Localization.NormTrace
import Mathlib.FieldTheory.IntermediateField.Adjoin.Algebra
import Mathlib.RingTheory.IsAdjoinRoot
import Mathlib.RingTheory.Polynomial.Resultant.Basic

#check PowerBasis.trace_gen_eq_nextCoeff_minpoly
#check PowerBasis.trace_gen_pow
#check PowerBasis.trace_gen_pow_eq_sum_roots
#check PowerBasis.minpoly_gen
#check Algebra.adjoin.powerBasis'_minpoly_gen
#check NoZeroSMulDivisors.algebraMap_injective
#check Submonoid.map_mk
#check Algebra.mem_algebraMapSubmonoid_of_mem
#check Basis.localizationLocalization_apply
#check PowerBasis.basis_eq_pow
#check PowerBasis.basis_apply
#check AdjoinRoot.powerBasis_gen
#check AdjoinRoot.powerBasis_basis
#check Algebra.discr_powerBasis_eq_prod
#check Fintype.bijective_iff_injective_and_card
#check Fintype.bijective_iff_injective_and_card_le
#check Equiv.ofBijective
#check Algebra.trace_algebraMap
#check Algebra.trace_add
#check Algebra.trace_mul
#check Algebra.traceMatrix_apply
#check Algebra.discr_def
#check Algebra.discr_reindex
#check Polynomial.discr_of_degree_eq_three
#check Polynomial.discr_eq_prod
#check Cusick.CubicOrder.signedDiscriminant
#check Cusick.CubicOrder.discriminant
#check Cusick.CubicOrder.regulator_lower_bound
#check NumberField.Units.regOfFamily_eq_det
#check NumberField.Units.regOfFamily_div_regulator
#check Subgroup.relIndex_mul_index
#check Subgroup.relIndex_eq_one

open ABCOrders
noncomputable example (P : Parameters) : Algebra (orderCarrier P) (ABCField P) := inferInstance
example (P : Parameters) : IsScalarTower ℤ (orderCarrier P) (ABCField P) := inferInstance
#check isLocalization_iff
#check isLocalization_iff_isLocalizationMap
#check multiple_mem_adjoin_of_mem_localization_adjoin
#check Algebra.adjoin_map
#check Algebra.map_adjoin
#check Algebra.adjoin_mono
#check Subalgebra.map_top
#check Subalgebra.mem_map
#check IsLocalization.Away.of_field
#check IsLocalization.of_field
#check Algebra.discr_localizationLocalization
#check Polynomial.discr_of_degree_eq_three
#check Algebra.adjoin.powerBasis'_minpoly_gen
